<script type="text/javascript">

    var imgPath = '<?php echo $this->baseUrl('images/');?>';

    // console.log(imgPath);

    $(document).ready(function() {
        openid.img_path = imgPath;
        openid.init('openid_identifier');
        openid.setDemoMode(false); //Stops form submission for client javascript-only test purposes

    });
</script>

<div>
    <!-- Simple OpenID Selector -->
    <form action="<?php echo $this->baseUrl('/user/login');?>" method="get" id="openid_form">
        <input type="hidden" name="action" value="verify" />
        <fieldset>
            <legend>Sign-in using</legend>
            <div id="openid_choice">
               
                <div id="openid_btns"></div>
            </div>
            <div id="openid_input_area">
                <input id="openid_identifier" name="openid_identifier" type="text" value="http://" />
                <input id="openid_submit" type="submit" value="Sign-In"/>
            </div>
            <noscript>
                <p>OpenID is service that allows you to log-on to many different websites using a single indentity.
				Find out <a href="http://openid.net/what/">more about OpenID</a> and <a href="http://openid.net/get/">how to get an OpenID enabled account</a>.</p>
            </noscript>
        </fieldset>
    </form>
    <!-- /Simple OpenID Selector -->
</div>